# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  database: book_registry
  password: 123456
  

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  database: book_registry
  password: 123456